# Generated by Django 3.2.10 on 2024-05-09 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
