# Generated by Django 3.2.10 on 2024-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_response_score'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='QuizResponse',
        ),
    ]
